services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/academia
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: academia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
