services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pulsefit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1233
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Porta AMQP
      - "15672:15672" # Porta do painel web RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api:
    build: .
    container_name: pulse_fit
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:1233@db:5432/pulsefit
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq

volumes:
  pgdata:
