# filepath: c:\Users\Pedro\Documents\Pacto_Teste\Dockerfile.consumer
FROM python:3.9-slim

WORKDIR /app

# Copie toda a estrutura do projeto para o container
COPY . .

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Comando para iniciar o consumidor
CMD ["python", "-m", "app.consumers.churn_consumer"]